apiVersion: v1
kind: Service
metadata:
  name: blue-svc
spec:
  selector:
    pod: blue
  ports:
    - protocol: TCP
      port: 80   # NodePort service port
      targetPort: 80   # Port on the pod
  type: NodePort
