apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-python-pod  # Update with your pod's labels
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  # Update with the port your application is listening on in the pod
  type: NodePort
